version: '3.4'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    command: server /data

  storage-service:
    build: .
    environment:
      PORT: 8000
    ports:
      - 8000:8000
