version: '3.4'

services:
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - ./data:/data
    ports:
      - '9000:9000'
      - '3000:3000'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: "minio server --console-address :3000 /data"

  storage-service:
    build: .
    environment:
      PORT: 8000
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_USE_SSL: false
    ports:
      - 8000:8000
